CREATE TABLE IF NOT EXISTS clients (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(30) UNIQUE NOT NULL,
  name VARCHAR(100),
  age INTEGER,
  city VARCHAR(100),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS leads (
  id SERIAL PRIMARY KEY,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  service_key VARCHAR(50),
  service_title VARCHAR(255),
  branch VARCHAR(50),
  photo_received BOOLEAN DEFAULT FALSE,
  photo_url TEXT,
  photo_media_id TEXT,
  preferred_date DATE,
  preferred_time VARCHAR(10),
  appointment_datetime TIMESTAMP,
  status VARCHAR(50) DEFAULT 'new',
  specialist VARCHAR(100),
  admin_comment TEXT,
  calendar_event_id TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
  id SERIAL PRIMARY KEY,
  phone VARCHAR(30) UNIQUE NOT NULL,
  step VARCHAR(50) NOT NULL,
  payload_json TEXT,
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE clients ADD COLUMN IF NOT EXISTS name VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE clients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

ALTER TABLE leads ADD COLUMN IF NOT EXISTS client_id INTEGER;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS service_key VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS service_title VARCHAR(255);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS branch VARCHAR(50);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS photo_received BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS photo_media_id TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS preferred_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS preferred_time VARCHAR(10);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS appointment_datetime TIMESTAMP;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'new';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS specialist VARCHAR(100);
ALTER TABLE leads ADD COLUMN IF NOT EXISTS admin_comment TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS calendar_event_id TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE leads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

ALTER TABLE sessions ADD COLUMN IF NOT EXISTS step VARCHAR(50);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS payload_json TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();